name: Otomatis Deploy ke Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH connection
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server via SSH
        run: |
          echo "CI/CD trigger commit: $(date -u +'%Y-%m-%dT%H:%M:%SZ')"

          ssh -p 21032 -o StrictHostKeyChecking=no \
          ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'

            set -e

            eval $(ssh-agent -s)
            ssh-add ~/.ssh/wisnu

            echo "Testing GitHub SSH..."
            ssh -T git@github.com || true

            cd web

            echo "Fetching latest code..."
            git fetch origin main

            echo "Reset to latest main..."
            git reset --hard origin/main

            echo "Laravel optimize clear..."
            php artisan optimize:clear

            echo "Running migration..."
            php artisan migrate --force

            echo "Caching config..."
            php artisan config:cache

            echo "Deploy selesai"

          EOF
