name: Otomatis Deploy ke Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup SSH connection
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to server via SSH
      run: |
        ssh -p 21032 -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "
            set -e
            eval \$(ssh-agent -s)
            ssh-add ~/.ssh/wisnu
            ssh -T git@github.com
            cd web
            git fetch origin main
            git checkout main
            git reset --hard origin/main
            composer install --no-interaction --prefer-dist --optimize-autoloader
            composer dump-autoload
            npm ci
            npm run build
            php artisan optimize:clear
            php artisan migrate --force
            php artisan db:seed --class='Database\\Seeders\\Admin\\RolePermissionSeeder' --force
            php artisan config:cache
            echo DEPLOYED_COMMIT=\$(git rev-parse --short HEAD)
        " 